language: node_js
node_js:
  - "6.4.0"
script:
  - echo "Deploying!"
branches:
    except:
      - dev
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
